# Generated by Django 3.2 on 2022-10-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenciasbanco',
            options={'managed': False, 'permissions': [('can_view_referencias_banco', 'Can view referencias banco')]},
        ),
    ]
