# Generated by Django 3.2 on 2022-10-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_referenciasbanco_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenciasbanco',
            options={'managed': False},
        ),
    ]
