# Generated by Django 3.2 on 2022-11-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_referenciasbanco_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciasConceptosBanco',
            fields=[
                ('cve_concepto', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_concepto', models.CharField(max_length=255)),
                ('concepto', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto_externo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recargo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_limite', models.BooleanField(help_text='Activar solo si se ingresa una fecha limite de pago.')),
                ('fecha_limite_pago', models.DateField(blank=True, max_length=10, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Concepto',
                'db_table': 'referencias_conceptos_banco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenciasServiciosBanco',
            fields=[
                ('cve_servicio', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_servicio', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'referencias_servicios_banco',
                'managed': False,
            },
        ),
    ]
