version: "3"

services:
    web-edcon:
        build: .
        image: edcon:v1.1
        container_name: edcon-app
        restart: always
        env_file:
            - .env
        command: python manage.py runserver --insecure 0.0.0.0:8002
        volumes:
            - .:/code
        ports:
            - 8002:8002
volumes:
    .:
