# Generated by Django 3.2 on 2022-09-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_estudiante_uts', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Estudiante UTS')),
                ('precio_persona_externa', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Persona Externa')),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, default='default-image-curso-620x600.jpg', null=True, upload_to='cursos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
