# Generated by Django 3.2 on 2023-07-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_curso', models.PositiveSmallIntegerField(choices=[(1, 'EdCon'), (2, 'Red Conocer')], default=1)),
                ('duracion', models.CharField(blank=True, help_text='Ejemplo 2 meses o 8 semanas', max_length=50, null=True, verbose_name='Duración del Curso')),
                ('precio_estudiante_uts', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Estudiante UTS')),
                ('precio_persona_externa', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Persona Externa')),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, default='default-image-curso-770x433.png', help_text='El tamaño de la imagen debe ser de 770 x 436 pixeles', null=True, upload_to='cursos')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='CursoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscrito', models.BooleanField(default=False)),
                ('estatus', models.PositiveSmallIntegerField(choices=[(1, 'En progreso'), (2, 'Completado'), (3, 'No completado')], default='En progreso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Curso Estudiante',
                'verbose_name_plural': 'Cursos Estudiantes',
            },
        ),
    ]
