# Generated by Django 3.2 on 2022-09-30 17:52

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('edcon', '0002_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('avatar', models.ImageField(blank=True, default='default.png', null=True, upload_to='avatar')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
            },
            bases=('usuarios.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
