# Generated by Django 3.2 on 2022-09-30 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edcon', '0004_cursoestudiante_estudiante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursoestudiante',
            old_name='alumno',
            new_name='estudiante',
        ),
        migrations.AddField(
            model_name='cursoestudiante',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edcon.instructor'),
            preserve_default=False,
        ),
    ]
