# Generated by Django 3.2 on 2022-11-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcon', '0005_auto_20220930_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
