# Generated by Django 3.2 on 2023-02-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcon', '0006_curso_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, default='default-image-curso-770x433.png', help_text='El tamaño de la imagen debe ser de 770 x 436 pixeles', null=True, upload_to='cursos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_usuario',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Estudiante UTS'), (2, 'Egresado UTS'), (3, 'Persona Externa'), (4, 'Personal Administrativo')]),
        ),
    ]
