# Generated by Django 3.2 on 2023-07-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcon', '0008_estudiante_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ejemplo 2 meses o 8 semanas', max_length=50, null=True, verbose_name='Duración del Curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo_curso',
            field=models.PositiveSmallIntegerField(choices=[(1, 'EdCon'), (2, 'Red Conocer')], default=1),
        ),
    ]
