# Generated by Django 3.2 on 2024-01-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edcon', '0010_alter_curso_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='avatar',
        ),
    ]
