# Generated by Django 3.2 on 2024-10-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcon', '0011_auto_20240124_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, null=True),
        ),
    ]
