# Generated by Django 3.2 on 2023-07-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificados', '0001_initial'),
        ('edcon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoestudiante',
            name='curso_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edcon.cursoestudiante'),
        ),
        migrations.AddField(
            model_name='certificadoestudiante',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.plantilla'),
        ),
    ]
