# Generated by Django 3.2 on 2023-05-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoalumno',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
