# Generated by Django 3.2 on 2023-06-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificados', '0001_initial'),
        ('gestion_escolar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoalumno',
            name='curso_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.cursoalumno'),
        ),
        migrations.AddField(
            model_name='certificadoalumno',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.plantilla'),
        ),
    ]
