# Generated by Django 3.2 on 2023-05-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edcon', '0007_auto_20230220_1059'),
        ('certificados', '0002_alter_certificadoalumno_folio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, null=True)),
                ('firma', models.TextField()),
                ('cadena', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('curso_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edcon.cursoestudiante')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificados.plantilla')),
            ],
            options={
                'verbose_name': 'Certificado Estudiante',
                'verbose_name_plural': 'Certificados Estudiante',
                'db_table': 'certificados_certificado_estudiante',
            },
        ),
    ]
