# Generated by Django 3.2 on 2023-05-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
