# Generated by Django 3.2 on 2023-06-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0003_encuestaalumno_encuestaestudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestaalumno',
            name='opcion',
        ),
        migrations.RemoveField(
            model_name='encuestaalumno',
            name='opciones_seleccionadas',
        ),
        migrations.RemoveField(
            model_name='encuestaestudiante',
            name='opcion',
        ),
        migrations.RemoveField(
            model_name='encuestaestudiante',
            name='opciones_seleccionadas',
        ),
    ]
