# Generated by Django 3.2 on 2023-05-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0004_rename_curso_estudiante_certificadoestudiante_curso_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='firma_rector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
