# Generated by Django 3.2 on 2023-06-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0005_auto_20230522_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla',
            name='firma_rector',
        ),
        migrations.RemoveField(
            model_name='plantilla',
            name='imagen',
        ),
        migrations.AddField(
            model_name='plantilla',
            name='plantilla_con_firma',
            field=models.ImageField(default='default-image-certi-850x1100.png', help_text='El tamaño de la imagen debe estar en múltiplos de 850 x 1100 pixeles', upload_to='certificados', verbose_name='Plantilla con Firma'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='plantilla_sin_firma',
            field=models.ImageField(default='default-image-certi-850x1100.png', help_text='El tamaño de la imagen debe estar en múltiplos de 850 x 1100 pixeles', upload_to='certificados', verbose_name='Plantilla sin Firma'),
        ),
    ]
