# Generated by Django 3.2 on 2023-05-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0005_auto_20230504_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='titulo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
