# Generated by Django 3.2 on 2023-05-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0006_certificado_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Logo', 'verbose_name_plural': 'Logos'},
        ),
    ]
