# Generated by Django 3.2 on 2023-06-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0006_auto_20230626_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestaestudiante',
            name='curso_alumno',
        ),
        migrations.RemoveField(
            model_name='encuestaestudiante',
            name='encuesta',
        ),
        migrations.RemoveField(
            model_name='encuestaestudiante',
            name='pregunta',
        ),
        migrations.DeleteModel(
            name='EncuestaAlumno',
        ),
        migrations.DeleteModel(
            name='EncuestaEstudiante',
        ),
    ]
