# Generated by Django 3.2 on 2023-07-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0007_auto_20230627_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='tipo_plantilla',
            field=models.CharField(choices=[('Constancia UTS', 'Constancia UTS'), ('Constancia Red Conocer', 'Constancia Red Conocer'), ('Cédula de Acreditación', 'Cédula de Acreditación'), ('Reconocimiento UTS', 'Reconocimiento UTS')], default='Constancia UTS', max_length=30, verbose_name='Tipo de Plantilla'),
        ),
    ]
