# Generated by Django 3.2 on 2023-05-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0009_alter_empresa_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
