# Generated by Django 3.2 on 2023-05-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0012_auto_20230504_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='nombre',
            new_name='tipo_documento',
        ),
    ]
