# Generated by Django 3.2 on 2023-05-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0013_rename_nombre_documento_tipo_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='tipo_documento',
            new_name='tipo_de_documento',
        ),
    ]
