# Generated by Django 3.2 on 2023-05-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0014_rename_tipo_documento_documento_tipo_de_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='tipo_de_documento',
            new_name='nombre',
        ),
    ]
