# Generated by Django 3.2 on 2023-05-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0015_rename_tipo_de_documento_documento_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='nombre',
            new_name='tipo',
        ),
    ]
