# Generated by Django 3.2 on 2023-05-04 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0016_rename_nombre_documento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificados.documento'),
        ),
    ]
