# Generated by Django 3.2 on 2023-05-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0018_alter_certificado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificados.empresa'),
        ),
    ]
