# Generated by Django 3.2 on 2023-05-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0019_alter_certificado_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='nombre',
            new_name='empresa',
        ),
    ]
