# Generated by Django 3.2 on 2023-05-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0020_rename_nombre_certificado_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='empresa',
            new_name='nombre',
        ),
    ]
