# Generated by Django 3.2 on 2023-05-04 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0021_rename_empresa_certificado_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificados.empresa'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
