# Generated by Django 3.2.13 on 2022-05-31 13:31

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.CharField(blank=True, max_length=60, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=60, null=True)),
                ('colonia', models.CharField(blank=True, max_length=60, null=True)),
                ('calle', models.CharField(blank=True, max_length=60, null=True)),
                ('num_exterior', models.CharField(blank=True, max_length=15, null=True)),
                ('num_interior', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo_usuario', models.PositiveSmallIntegerField(choices=[(1, 'Estudiante UTS'), (2, 'Egresado UTS'), (3, 'Persona Externa')])),
                ('avatar', models.ImageField(blank=True, default='default.png', null=True, upload_to='avatar')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
            bases=('usuarios.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
