# Generated by Django 3.2.13 on 2022-05-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='avatar'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='calle',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ciudad',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='colonia',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='num_exterior',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='num_interior',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tipo_usuario',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Estudiante UTS'), (2, 'Egresado UTS'), (3, 'Persona Externa')], null=True),
        ),
    ]
