# Generated by Django 3.2 on 2022-09-30 14:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacioncurso',
            name='calificacion_final',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Calificación Final'),
        ),
        migrations.AlterField(
            model_name='calificacioncurso',
            name='primer_examen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Primer Examen'),
        ),
        migrations.AlterField(
            model_name='calificacioncurso',
            name='segundo_examen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Segundo Examen'),
        ),
    ]
