# Generated by Django 3.2 on 2023-06-16 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacioncursosemanal',
            name='curso_alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calicursosem', to='gestion_escolar.cursoalumno'),
        ),
    ]
