# Generated by Django 3.2 on 2022-06-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_examen', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Primer Examen')),
                ('segundo_examen', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Segundo Examen')),
                ('calificacion_final', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Calificacion Final')),
            ],
        ),
    ]
