# Generated by Django 3.2 on 2023-05-22 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_carrera'),
        ('gestion_escolar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.carrera'),
        ),
    ]
