# Generated by Django 3.2 on 2022-11-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0002_auto_20220930_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
