# Generated by Django 3.2 on 2022-06-20 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0002_calificacioncurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacioncurso',
            name='curso_alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.cursoalumno'),
            preserve_default=False,
        ),
    ]
