# Generated by Django 3.2 on 2023-05-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_carrera'),
        ('gestion_escolar', '0002_alumno_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(blank=True, help_text='Selecciona una opción solo si es estudiante o egresado UTS', null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.carrera'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, default='cursos/default-image-curso-770x433.png', help_text='El tamaño de la imagen debe ser de 770 x 436 pixeles', null=True, upload_to='cursos'),
        ),
    ]
