# Generated by Django 3.2 on 2023-06-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0003_auto_20230526_1120'),
        ('gestion_escolar', '0003_auto_20230526_1137'),
    ]

    operations = [
    ]
