# Generated by Django 3.2 on 2023-06-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0004_merge_0003_auto_20230526_1120_0003_auto_20230526_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoalumno',
            name='horario',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Semanal', 'Semanal'), ('Sabatino', 'Sabatino')], null=True),
        ),
    ]
