# Generated by Django 3.2 on 2022-11-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0004_remove_curso_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
