# Generated by Django 3.2 on 2022-11-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0005_curso_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, default='default-image-curso-770x433.png', help_text='El tamaño de la imagen debe ser de 770 x 436 pixeles', null=True, upload_to='cursos'),
        ),
    ]
