# Generated by Django 3.2 on 2023-06-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0006_calificacioncursosabatino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoalumno',
            name='horario',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', 'Semanal'), ('2', 'Sabatino')], null=True),
        ),
    ]
