# Generated by Django 3.2 on 2023-06-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0007_alter_cursoalumno_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoalumno',
            name='horario',
            field=models.CharField(blank=True, choices=[('Semanal', 'Semanal'), ('Sabatino', 'Sabatino')], max_length=10, null=True),
        ),
    ]
