# Generated by Django 3.2 on 2022-11-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0007_auto_20221118_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='curso',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
