# Generated by Django 3.2 on 2022-11-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0008_aspirante_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aspirante',
        ),
    ]
