# Generated by Django 3.2 on 2023-06-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0008_alter_cursoalumno_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoalumno',
            name='horario',
            field=models.CharField(choices=[('Semanal', 'Semanal'), ('Sabatino', 'Sabatino')], default='Semanal', max_length=10),
        ),
    ]
