# Generated by Django 3.2 on 2023-05-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0009_delete_aspirante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='tipo_usuario',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Estudiante UTS'), (2, 'Egresado UTS'), (3, 'Persona Externa'), (4, 'Personal Administrativo')]),
        ),
    ]
