# Generated by Django 3.2 on 2023-02-20 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0009_delete_aspirante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.CharField(max_length=10)),
                ('num_aula', models.CharField(max_length=10, verbose_name='Número de aula')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.AlterField(
            model_name='alumno',
            name='tipo_usuario',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Estudiante UTS'), (2, 'Egresado UTS'), (3, 'Persona Externa'), (4, 'Personal Administrativo')]),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('alumnos', models.ManyToManyField(blank=True, related_name='grupo_alumnos', through='gestion_escolar.CursoAlumno', to='gestion_escolar.Alumno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.aula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.curso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.periodo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.profesor')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.AddField(
            model_name='cursoalumno',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.grupo'),
        ),
    ]
