# Generated by Django 3.2 on 2023-06-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0009_alter_cursoalumno_horario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalificacionCursoSabatino',
            new_name='CalificacionCursoSemanal',
        ),
        migrations.AlterField(
            model_name='cursoalumno',
            name='horario',
            field=models.CharField(choices=[('Sabatino', 'Sabatino'), ('Semanal', 'Semanal')], default='Sabatino', max_length=10),
        ),
    ]
