# Generated by Django 3.2 on 2023-02-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0010_auto_20230220_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='alumnos',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='cursoalumno',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
