# Generated by Django 3.2 on 2023-06-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0010_auto_20230615_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacioncurso',
            options={'verbose_name': 'Calificacion Curso Sabatino', 'verbose_name_plural': 'Calificaciones Curso Sabatino'},
        ),
        migrations.AlterModelOptions(
            name='calificacioncursosemanal',
            options={'verbose_name': 'Calificacion Curso Semanal', 'verbose_name_plural': 'Calificaciones Curso Semanal'},
        ),
    ]
