# Generated by Django 3.2 on 2023-05-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_carrera'),
        ('gestion_escolar', '0010_alter_alumno_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.carrera'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, default='', help_text='El tamaño de la imagen debe ser de 770 x 436 pixeles', null=True, upload_to='cursos'),
        ),
    ]
