# Generated by Django 3.2 on 2023-06-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0011_auto_20230616_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacioncurso',
            options={'verbose_name': 'Calificacion', 'verbose_name_plural': 'Calificaciones'},
        ),
    ]
