# Generated by Django 3.2 on 2023-05-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0011_auto_20230522_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, default='cursos/default-image-curso-770x433.png', help_text='El tamaño de la imagen debe ser de 770 x 436 pixeles', null=True, upload_to='cursos'),
        ),
    ]
