# Generated by Django 3.2 on 2023-05-15 16:14

from django.db import migrations, models
import gestion_escolar.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0012_alter_curso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoalumno',
            name='folio',
            field=models.CharField(blank=True, default=gestion_escolar.models.incrementarFolio, max_length=8, null=True),
        ),
    ]
