# Generated by Django 3.2 on 2023-07-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0013_alter_alumno_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
