# Generated by Django 3.2 on 2023-10-17 18:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0014_alumno_edad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacioncurso',
            options={'verbose_name': 'Calificacion Curso Sabatino', 'verbose_name_plural': 'Calificaciones Curso Sabatino'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AddField(
            model_name='cursoalumno',
            name='horario',
            field=models.CharField(choices=[('SA', 'Sabatino'), ('SE', 'Semanal')], default='Sabatino', max_length=10),
        ),
        migrations.AlterField(
            model_name='calificacioncurso',
            name='curso_alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calicurso', to='gestion_escolar.cursoalumno'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CalificacionCursoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_final', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Calificación Final')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('curso_alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calicursosem', to='gestion_escolar.cursoalumno')),
            ],
            options={
                'verbose_name': 'Calificacion Curso Semanal',
                'verbose_name_plural': 'Calificaciones Curso Semanal',
            },
        ),
    ]
