# Generated by Django 3.2 on 2023-12-01 15:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0015_auto_20231017_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='cursoalumno',
            name='horario',
            field=models.CharField(choices=[('SA', 'Sabatino'), ('SE', 'Semanal')], default='SA', max_length=10),
        ),
    ]
