# Generated by Django 3.2 on 2023-06-21 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='seccion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='encuestas.seccion'),
            preserve_default=False,
        ),
    ]
