# Generated by Django 3.2 on 2023-06-22 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_seccion_encuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='encuesta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuesta'),
            preserve_default=False,
        ),
    ]
