# Generated by Django 3.2 on 2023-06-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_alter_seccion_encuesta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcion',
            old_name='pregunta',
            new_name='preguntas',
        ),
    ]
