# Generated by Django 3.2 on 2023-06-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0006_auto_20230626_1028'),
        ('encuestas', '0008_opcion_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='encuesta',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='opcion',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Opcion',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
