# Generated by Django 3.2 on 2023-06-27 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0002_alter_calificacioncursosemanal_curso_alumno'),
        ('edcon', '0008_estudiante_carrera'),
        ('encuestas', '0009_auto_20230626_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('curso_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edcon.cursoestudiante')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.pregunta')),
            ],
            options={
                'verbose_name': 'Encuesta de Evalución del Servicio EDCON',
                'verbose_name_plural': 'Encuestas de Evaluación del Servicio EDCON',
            },
        ),
        migrations.CreateModel(
            name='EncuestaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('curso_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.cursoalumno')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.pregunta')),
            ],
            options={
                'verbose_name': 'Encuesta de Evalución del Servicio CELE',
                'verbose_name_plural': 'Encuestas de Evaluación del Servicio CELE',
            },
        ),
    ]
