# Generated by Django 3.2 on 2023-06-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0015_registroscele_registrosedcon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestaestudiante',
            name='curso_alumno',
        ),
        migrations.RemoveField(
            model_name='encuestaestudiante',
            name='encuesta',
        ),
        migrations.RemoveField(
            model_name='encuestaestudiante',
            name='pregunta',
        ),
        migrations.DeleteModel(
            name='EncuestaAlumno',
        ),
        migrations.DeleteModel(
            name='EncuestaEstudiante',
        ),
    ]
