# Generated by Django 3.2 on 2023-06-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0017_encuestaalumno_encuestaestudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestaestudiante',
            name='curso_alumno',
        ),
        migrations.RemoveField(
            model_name='encuestaestudiante',
            name='encuesta',
        ),
        migrations.RemoveField(
            model_name='encuestaestudiante',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='encuestaestudiante',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='registroscele',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='registrosedcon',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='EncuestaAlumno',
        ),
        migrations.DeleteModel(
            name='EncuestaEstudiante',
        ),
        migrations.DeleteModel(
            name='RegistrosCELE',
        ),
        migrations.DeleteModel(
            name='RegistrosEDCON',
        ),
    ]
