# Generated by Django 3.2 on 2023-06-28 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edcon', '0008_estudiante_carrera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_escolar', '0002_alter_calificacioncursosemanal_curso_alumno'),
        ('encuestas', '0018_auto_20230628_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrosEDCON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('curso_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edcon.cursoestudiante')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro EDCON',
                'verbose_name_plural': 'Registros EDCON',
            },
        ),
        migrations.CreateModel(
            name='RegistrosCELE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('curso_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.cursoalumno')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro CELE',
                'verbose_name_plural': 'Registros CELE',
            },
        ),
        migrations.CreateModel(
            name='EncuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('curso_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edcon.cursoestudiante')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.pregunta')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.registrosedcon')),
            ],
            options={
                'verbose_name': 'Encuesta de Evalución del Servicio EDCON',
                'verbose_name_plural': 'Encuestas de Evaluación del Servicio EDCON',
            },
        ),
        migrations.CreateModel(
            name='EncuestaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('curso_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.cursoalumno')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.pregunta')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.registroscele')),
            ],
            options={
                'verbose_name': 'Encuesta de Evalución del Servicio CELE',
                'verbose_name_plural': 'Encuestas de Evaluación del Servicio CELE',
            },
        ),
    ]
